#logging:
#    level:
#        root: WARN
config:
    api:
        key: eecc9cf7ce200ae5dcf4d50456dc64d4
aws:
    dynamodb:
        endpoint: arn:aws:dynamodb:us-east-1:540307084625:table/WeatherData
    accessKey: AKIAVA5YLES6JMFCU43M
    secretKey: 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