#logging:
#    level:
#        root: WARN
config:
    api:
        key: eecc9cf7ce200ae5dcf4d50456dc64d4
aws:
    dynamodb:
        endpoint: arn:aws:dynamodb:us-east-1:540307084625:table/WeatherData
    accessKey: AKIAW3MEAAWTDYTC7WXM
    secretKey: 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