#logging:
#    level:
#        root: WARN
config:
    api:
        key: eecc9cf7ce200ae5dcf4d50456dc64d4
aws:
    dynamodb:
        endpoint: arn:aws:dynamodb:us-east-1:540307084625:table/WeatherData
    accessKey: AKIAVA5YLES6GPTZQ7HV
    secretKey: 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